<?php
namespace MMIStandard;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class Constant extends \Thrift\Type\TConstant
{
    static protected $MSimulationEvent_Start;
    static protected $MSimulationEvent_Ready;
    static protected $MSimulationEvent_Stroke_Start;
    static protected $MSimulationEvent_Stroke;
    static protected $MSimulationEvent_Stroke_End;
    static protected $MSimulationEvent_End;
    static protected $MSimulationEvent_Abort;
    static protected $MSimulationEvent_Warning;
    static protected $MSimulationEvent_Exception;
    static protected $MSimulationEvent_InitError;
    static protected $MSimulationEvent_CycleEnd;

    protected static function init_MSimulationEvent_Start()
    {
        return "start";
    }

    protected static function init_MSimulationEvent_Ready()
    {
        return "ready";
    }

    protected static function init_MSimulationEvent_Stroke_Start()
    {
        return "stroke_start";
    }

    protected static function init_MSimulationEvent_Stroke()
    {
        return "stroke";
    }

    protected static function init_MSimulationEvent_Stroke_End()
    {
        return "stroke_end";
    }

    protected static function init_MSimulationEvent_End()
    {
        return "end";
    }

    protected static function init_MSimulationEvent_Abort()
    {
        return "abort";
    }

    protected static function init_MSimulationEvent_Warning()
    {
        return "warning";
    }

    protected static function init_MSimulationEvent_Exception()
    {
        return "exception";
    }

    protected static function init_MSimulationEvent_InitError()
    {
        return "initError";
    }

    protected static function init_MSimulationEvent_CycleEnd()
    {
        return "cycleEnd";
    }
}
