/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.mosim.mmi.constraints;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-09-24")
public class MTranslationConstraint implements org.apache.thrift.TBase<MTranslationConstraint, MTranslationConstraint._Fields>, java.io.Serializable, Cloneable, Comparable<MTranslationConstraint> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MTranslationConstraint");

  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("Type", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField LIMITS_FIELD_DESC = new org.apache.thrift.protocol.TField("Limits", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MTranslationConstraintStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MTranslationConstraintTupleSchemeFactory();

  /**
   * 
   * @see MTranslationConstraintType
   */
  public @org.apache.thrift.annotation.Nullable MTranslationConstraintType Type; // required
  public @org.apache.thrift.annotation.Nullable MInterval3 Limits; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see MTranslationConstraintType
     */
    TYPE((short)1, "Type"),
    LIMITS((short)2, "Limits");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // LIMITS
          return LIMITS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("Type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, MTranslationConstraintType.class)));
    tmpMap.put(_Fields.LIMITS, new org.apache.thrift.meta_data.FieldMetaData("Limits", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MInterval3.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MTranslationConstraint.class, metaDataMap);
  }

  public MTranslationConstraint() {
  }

  public MTranslationConstraint(
    MTranslationConstraintType Type,
    MInterval3 Limits)
  {
    this();
    this.Type = Type;
    this.Limits = Limits;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MTranslationConstraint(MTranslationConstraint other) {
    if (other.isSetType()) {
      this.Type = other.Type;
    }
    if (other.isSetLimits()) {
      this.Limits = new MInterval3(other.Limits);
    }
  }

  public MTranslationConstraint deepCopy() {
    return new MTranslationConstraint(this);
  }

  @Override
  public void clear() {
    this.Type = null;
    this.Limits = null;
  }

  /**
   * 
   * @see MTranslationConstraintType
   */
  @org.apache.thrift.annotation.Nullable
  public MTranslationConstraintType getType() {
    return this.Type;
  }

  /**
   * 
   * @see MTranslationConstraintType
   */
  public MTranslationConstraint setType(@org.apache.thrift.annotation.Nullable MTranslationConstraintType Type) {
    this.Type = Type;
    return this;
  }

  public void unsetType() {
    this.Type = null;
  }

  /** Returns true if field Type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.Type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.Type = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public MInterval3 getLimits() {
    return this.Limits;
  }

  public MTranslationConstraint setLimits(@org.apache.thrift.annotation.Nullable MInterval3 Limits) {
    this.Limits = Limits;
    return this;
  }

  public void unsetLimits() {
    this.Limits = null;
  }

  /** Returns true if field Limits is set (has been assigned a value) and false otherwise */
  public boolean isSetLimits() {
    return this.Limits != null;
  }

  public void setLimitsIsSet(boolean value) {
    if (!value) {
      this.Limits = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((MTranslationConstraintType)value);
      }
      break;

    case LIMITS:
      if (value == null) {
        unsetLimits();
      } else {
        setLimits((MInterval3)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case LIMITS:
      return getLimits();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case LIMITS:
      return isSetLimits();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof MTranslationConstraint)
      return this.equals((MTranslationConstraint)that);
    return false;
  }

  public boolean equals(MTranslationConstraint that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Type = true && this.isSetType();
    boolean that_present_Type = true && that.isSetType();
    if (this_present_Type || that_present_Type) {
      if (!(this_present_Type && that_present_Type))
        return false;
      if (!this.Type.equals(that.Type))
        return false;
    }

    boolean this_present_Limits = true && this.isSetLimits();
    boolean that_present_Limits = true && that.isSetLimits();
    if (this_present_Limits || that_present_Limits) {
      if (!(this_present_Limits && that_present_Limits))
        return false;
      if (!this.Limits.equals(that.Limits))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
    if (isSetType())
      hashCode = hashCode * 8191 + Type.getValue();

    hashCode = hashCode * 8191 + ((isSetLimits()) ? 131071 : 524287);
    if (isSetLimits())
      hashCode = hashCode * 8191 + Limits.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MTranslationConstraint other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Type, other.Type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLimits()).compareTo(other.isSetLimits());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLimits()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Limits, other.Limits);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MTranslationConstraint(");
    boolean first = true;

    sb.append("Type:");
    if (this.Type == null) {
      sb.append("null");
    } else {
      sb.append(this.Type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Limits:");
    if (this.Limits == null) {
      sb.append("null");
    } else {
      sb.append(this.Limits);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (Type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'Type' was not present! Struct: " + toString());
    }
    if (Limits == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'Limits' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (Limits != null) {
      Limits.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MTranslationConstraintStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MTranslationConstraintStandardScheme getScheme() {
      return new MTranslationConstraintStandardScheme();
    }
  }

  private static class MTranslationConstraintStandardScheme extends org.apache.thrift.scheme.StandardScheme<MTranslationConstraint> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MTranslationConstraint struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Type = de.mosim.mmi.constraints.MTranslationConstraintType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LIMITS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.Limits = new MInterval3();
              struct.Limits.read(iprot);
              struct.setLimitsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MTranslationConstraint struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.Type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.Limits != null) {
        oprot.writeFieldBegin(LIMITS_FIELD_DESC);
        struct.Limits.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MTranslationConstraintTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MTranslationConstraintTupleScheme getScheme() {
      return new MTranslationConstraintTupleScheme();
    }
  }

  private static class MTranslationConstraintTupleScheme extends org.apache.thrift.scheme.TupleScheme<MTranslationConstraint> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MTranslationConstraint struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.Type.getValue());
      struct.Limits.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MTranslationConstraint struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.Type = de.mosim.mmi.constraints.MTranslationConstraintType.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      struct.Limits = new MInterval3();
      struct.Limits.read(iprot);
      struct.setLimitsIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

