/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.mosim.mmi.scene;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-10-20")
public class MSceneObject implements org.apache.thrift.TBase<MSceneObject, MSceneObject._Fields>, java.io.Serializable, Cloneable, Comparable<MSceneObject> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MSceneObject");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("Name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TRANSFORM_FIELD_DESC = new org.apache.thrift.protocol.TField("Transform", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField COLLIDER_FIELD_DESC = new org.apache.thrift.protocol.TField("Collider", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField MESH_FIELD_DESC = new org.apache.thrift.protocol.TField("Mesh", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField PHYSICS_PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("PhysicsProperties", org.apache.thrift.protocol.TType.STRUCT, (short)6);
  private static final org.apache.thrift.protocol.TField PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("Properties", org.apache.thrift.protocol.TType.MAP, (short)8);
  private static final org.apache.thrift.protocol.TField ATTACHMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("Attachments", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField CONSTRAINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("Constraints", org.apache.thrift.protocol.TType.LIST, (short)10);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MSceneObjectStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MSceneObjectTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String ID; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String Name; // required
  public @org.apache.thrift.annotation.Nullable de.mosim.mmi.math.MTransform Transform; // required
  public @org.apache.thrift.annotation.Nullable MCollider Collider; // optional
  public @org.apache.thrift.annotation.Nullable MMesh Mesh; // optional
  public @org.apache.thrift.annotation.Nullable MPhysicsProperties PhysicsProperties; // optional
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> Properties; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<MAttachment> Attachments; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<de.mosim.mmi.constraints.MConstraint> Constraints; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "ID"),
    NAME((short)2, "Name"),
    TRANSFORM((short)3, "Transform"),
    COLLIDER((short)4, "Collider"),
    MESH((short)5, "Mesh"),
    PHYSICS_PROPERTIES((short)6, "PhysicsProperties"),
    PROPERTIES((short)8, "Properties"),
    ATTACHMENTS((short)9, "Attachments"),
    CONSTRAINTS((short)10, "Constraints");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NAME
          return NAME;
        case 3: // TRANSFORM
          return TRANSFORM;
        case 4: // COLLIDER
          return COLLIDER;
        case 5: // MESH
          return MESH;
        case 6: // PHYSICS_PROPERTIES
          return PHYSICS_PROPERTIES;
        case 8: // PROPERTIES
          return PROPERTIES;
        case 9: // ATTACHMENTS
          return ATTACHMENTS;
        case 10: // CONSTRAINTS
          return CONSTRAINTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.COLLIDER,_Fields.MESH,_Fields.PHYSICS_PROPERTIES,_Fields.PROPERTIES,_Fields.ATTACHMENTS,_Fields.CONSTRAINTS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("ID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("Name", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TRANSFORM, new org.apache.thrift.meta_data.FieldMetaData("Transform", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, de.mosim.mmi.math.MTransform.class)));
    tmpMap.put(_Fields.COLLIDER, new org.apache.thrift.meta_data.FieldMetaData("Collider", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MCollider.class)));
    tmpMap.put(_Fields.MESH, new org.apache.thrift.meta_data.FieldMetaData("Mesh", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MMesh.class)));
    tmpMap.put(_Fields.PHYSICS_PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("PhysicsProperties", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MPhysicsProperties.class)));
    tmpMap.put(_Fields.PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("Properties", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ATTACHMENTS, new org.apache.thrift.meta_data.FieldMetaData("Attachments", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MAttachment.class))));
    tmpMap.put(_Fields.CONSTRAINTS, new org.apache.thrift.meta_data.FieldMetaData("Constraints", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, de.mosim.mmi.constraints.MConstraint.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MSceneObject.class, metaDataMap);
  }

  public MSceneObject() {
  }

  public MSceneObject(
    java.lang.String ID,
    java.lang.String Name,
    de.mosim.mmi.math.MTransform Transform)
  {
    this();
    this.ID = ID;
    this.Name = Name;
    this.Transform = Transform;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MSceneObject(MSceneObject other) {
    if (other.isSetID()) {
      this.ID = other.ID;
    }
    if (other.isSetName()) {
      this.Name = other.Name;
    }
    if (other.isSetTransform()) {
      this.Transform = new de.mosim.mmi.math.MTransform(other.Transform);
    }
    if (other.isSetCollider()) {
      this.Collider = new MCollider(other.Collider);
    }
    if (other.isSetMesh()) {
      this.Mesh = new MMesh(other.Mesh);
    }
    if (other.isSetPhysicsProperties()) {
      this.PhysicsProperties = new MPhysicsProperties(other.PhysicsProperties);
    }
    if (other.isSetProperties()) {
      java.util.Map<java.lang.String,java.lang.String> __this__Properties = new java.util.HashMap<java.lang.String,java.lang.String>(other.Properties);
      this.Properties = __this__Properties;
    }
    if (other.isSetAttachments()) {
      java.util.List<MAttachment> __this__Attachments = new java.util.ArrayList<MAttachment>(other.Attachments.size());
      for (MAttachment other_element : other.Attachments) {
        __this__Attachments.add(new MAttachment(other_element));
      }
      this.Attachments = __this__Attachments;
    }
    if (other.isSetConstraints()) {
      java.util.List<de.mosim.mmi.constraints.MConstraint> __this__Constraints = new java.util.ArrayList<de.mosim.mmi.constraints.MConstraint>(other.Constraints.size());
      for (de.mosim.mmi.constraints.MConstraint other_element : other.Constraints) {
        __this__Constraints.add(new de.mosim.mmi.constraints.MConstraint(other_element));
      }
      this.Constraints = __this__Constraints;
    }
  }

  public MSceneObject deepCopy() {
    return new MSceneObject(this);
  }

  @Override
  public void clear() {
    this.ID = null;
    this.Name = null;
    this.Transform = null;
    this.Collider = null;
    this.Mesh = null;
    this.PhysicsProperties = null;
    this.Properties = null;
    this.Attachments = null;
    this.Constraints = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getID() {
    return this.ID;
  }

  public MSceneObject setID(@org.apache.thrift.annotation.Nullable java.lang.String ID) {
    this.ID = ID;
    return this;
  }

  public void unsetID() {
    this.ID = null;
  }

  /** Returns true if field ID is set (has been assigned a value) and false otherwise */
  public boolean isSetID() {
    return this.ID != null;
  }

  public void setIDIsSet(boolean value) {
    if (!value) {
      this.ID = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getName() {
    return this.Name;
  }

  public MSceneObject setName(@org.apache.thrift.annotation.Nullable java.lang.String Name) {
    this.Name = Name;
    return this;
  }

  public void unsetName() {
    this.Name = null;
  }

  /** Returns true if field Name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.Name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.Name = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public de.mosim.mmi.math.MTransform getTransform() {
    return this.Transform;
  }

  public MSceneObject setTransform(@org.apache.thrift.annotation.Nullable de.mosim.mmi.math.MTransform Transform) {
    this.Transform = Transform;
    return this;
  }

  public void unsetTransform() {
    this.Transform = null;
  }

  /** Returns true if field Transform is set (has been assigned a value) and false otherwise */
  public boolean isSetTransform() {
    return this.Transform != null;
  }

  public void setTransformIsSet(boolean value) {
    if (!value) {
      this.Transform = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public MCollider getCollider() {
    return this.Collider;
  }

  public MSceneObject setCollider(@org.apache.thrift.annotation.Nullable MCollider Collider) {
    this.Collider = Collider;
    return this;
  }

  public void unsetCollider() {
    this.Collider = null;
  }

  /** Returns true if field Collider is set (has been assigned a value) and false otherwise */
  public boolean isSetCollider() {
    return this.Collider != null;
  }

  public void setColliderIsSet(boolean value) {
    if (!value) {
      this.Collider = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public MMesh getMesh() {
    return this.Mesh;
  }

  public MSceneObject setMesh(@org.apache.thrift.annotation.Nullable MMesh Mesh) {
    this.Mesh = Mesh;
    return this;
  }

  public void unsetMesh() {
    this.Mesh = null;
  }

  /** Returns true if field Mesh is set (has been assigned a value) and false otherwise */
  public boolean isSetMesh() {
    return this.Mesh != null;
  }

  public void setMeshIsSet(boolean value) {
    if (!value) {
      this.Mesh = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public MPhysicsProperties getPhysicsProperties() {
    return this.PhysicsProperties;
  }

  public MSceneObject setPhysicsProperties(@org.apache.thrift.annotation.Nullable MPhysicsProperties PhysicsProperties) {
    this.PhysicsProperties = PhysicsProperties;
    return this;
  }

  public void unsetPhysicsProperties() {
    this.PhysicsProperties = null;
  }

  /** Returns true if field PhysicsProperties is set (has been assigned a value) and false otherwise */
  public boolean isSetPhysicsProperties() {
    return this.PhysicsProperties != null;
  }

  public void setPhysicsPropertiesIsSet(boolean value) {
    if (!value) {
      this.PhysicsProperties = null;
    }
  }

  public int getPropertiesSize() {
    return (this.Properties == null) ? 0 : this.Properties.size();
  }

  public void putToProperties(java.lang.String key, java.lang.String val) {
    if (this.Properties == null) {
      this.Properties = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.Properties.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getProperties() {
    return this.Properties;
  }

  public MSceneObject setProperties(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> Properties) {
    this.Properties = Properties;
    return this;
  }

  public void unsetProperties() {
    this.Properties = null;
  }

  /** Returns true if field Properties is set (has been assigned a value) and false otherwise */
  public boolean isSetProperties() {
    return this.Properties != null;
  }

  public void setPropertiesIsSet(boolean value) {
    if (!value) {
      this.Properties = null;
    }
  }

  public int getAttachmentsSize() {
    return (this.Attachments == null) ? 0 : this.Attachments.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<MAttachment> getAttachmentsIterator() {
    return (this.Attachments == null) ? null : this.Attachments.iterator();
  }

  public void addToAttachments(MAttachment elem) {
    if (this.Attachments == null) {
      this.Attachments = new java.util.ArrayList<MAttachment>();
    }
    this.Attachments.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<MAttachment> getAttachments() {
    return this.Attachments;
  }

  public MSceneObject setAttachments(@org.apache.thrift.annotation.Nullable java.util.List<MAttachment> Attachments) {
    this.Attachments = Attachments;
    return this;
  }

  public void unsetAttachments() {
    this.Attachments = null;
  }

  /** Returns true if field Attachments is set (has been assigned a value) and false otherwise */
  public boolean isSetAttachments() {
    return this.Attachments != null;
  }

  public void setAttachmentsIsSet(boolean value) {
    if (!value) {
      this.Attachments = null;
    }
  }

  public int getConstraintsSize() {
    return (this.Constraints == null) ? 0 : this.Constraints.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<de.mosim.mmi.constraints.MConstraint> getConstraintsIterator() {
    return (this.Constraints == null) ? null : this.Constraints.iterator();
  }

  public void addToConstraints(de.mosim.mmi.constraints.MConstraint elem) {
    if (this.Constraints == null) {
      this.Constraints = new java.util.ArrayList<de.mosim.mmi.constraints.MConstraint>();
    }
    this.Constraints.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<de.mosim.mmi.constraints.MConstraint> getConstraints() {
    return this.Constraints;
  }

  public MSceneObject setConstraints(@org.apache.thrift.annotation.Nullable java.util.List<de.mosim.mmi.constraints.MConstraint> Constraints) {
    this.Constraints = Constraints;
    return this;
  }

  public void unsetConstraints() {
    this.Constraints = null;
  }

  /** Returns true if field Constraints is set (has been assigned a value) and false otherwise */
  public boolean isSetConstraints() {
    return this.Constraints != null;
  }

  public void setConstraintsIsSet(boolean value) {
    if (!value) {
      this.Constraints = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetID();
      } else {
        setID((java.lang.String)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case TRANSFORM:
      if (value == null) {
        unsetTransform();
      } else {
        setTransform((de.mosim.mmi.math.MTransform)value);
      }
      break;

    case COLLIDER:
      if (value == null) {
        unsetCollider();
      } else {
        setCollider((MCollider)value);
      }
      break;

    case MESH:
      if (value == null) {
        unsetMesh();
      } else {
        setMesh((MMesh)value);
      }
      break;

    case PHYSICS_PROPERTIES:
      if (value == null) {
        unsetPhysicsProperties();
      } else {
        setPhysicsProperties((MPhysicsProperties)value);
      }
      break;

    case PROPERTIES:
      if (value == null) {
        unsetProperties();
      } else {
        setProperties((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    case ATTACHMENTS:
      if (value == null) {
        unsetAttachments();
      } else {
        setAttachments((java.util.List<MAttachment>)value);
      }
      break;

    case CONSTRAINTS:
      if (value == null) {
        unsetConstraints();
      } else {
        setConstraints((java.util.List<de.mosim.mmi.constraints.MConstraint>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getID();

    case NAME:
      return getName();

    case TRANSFORM:
      return getTransform();

    case COLLIDER:
      return getCollider();

    case MESH:
      return getMesh();

    case PHYSICS_PROPERTIES:
      return getPhysicsProperties();

    case PROPERTIES:
      return getProperties();

    case ATTACHMENTS:
      return getAttachments();

    case CONSTRAINTS:
      return getConstraints();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetID();
    case NAME:
      return isSetName();
    case TRANSFORM:
      return isSetTransform();
    case COLLIDER:
      return isSetCollider();
    case MESH:
      return isSetMesh();
    case PHYSICS_PROPERTIES:
      return isSetPhysicsProperties();
    case PROPERTIES:
      return isSetProperties();
    case ATTACHMENTS:
      return isSetAttachments();
    case CONSTRAINTS:
      return isSetConstraints();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof MSceneObject)
      return this.equals((MSceneObject)that);
    return false;
  }

  public boolean equals(MSceneObject that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ID = true && this.isSetID();
    boolean that_present_ID = true && that.isSetID();
    if (this_present_ID || that_present_ID) {
      if (!(this_present_ID && that_present_ID))
        return false;
      if (!this.ID.equals(that.ID))
        return false;
    }

    boolean this_present_Name = true && this.isSetName();
    boolean that_present_Name = true && that.isSetName();
    if (this_present_Name || that_present_Name) {
      if (!(this_present_Name && that_present_Name))
        return false;
      if (!this.Name.equals(that.Name))
        return false;
    }

    boolean this_present_Transform = true && this.isSetTransform();
    boolean that_present_Transform = true && that.isSetTransform();
    if (this_present_Transform || that_present_Transform) {
      if (!(this_present_Transform && that_present_Transform))
        return false;
      if (!this.Transform.equals(that.Transform))
        return false;
    }

    boolean this_present_Collider = true && this.isSetCollider();
    boolean that_present_Collider = true && that.isSetCollider();
    if (this_present_Collider || that_present_Collider) {
      if (!(this_present_Collider && that_present_Collider))
        return false;
      if (!this.Collider.equals(that.Collider))
        return false;
    }

    boolean this_present_Mesh = true && this.isSetMesh();
    boolean that_present_Mesh = true && that.isSetMesh();
    if (this_present_Mesh || that_present_Mesh) {
      if (!(this_present_Mesh && that_present_Mesh))
        return false;
      if (!this.Mesh.equals(that.Mesh))
        return false;
    }

    boolean this_present_PhysicsProperties = true && this.isSetPhysicsProperties();
    boolean that_present_PhysicsProperties = true && that.isSetPhysicsProperties();
    if (this_present_PhysicsProperties || that_present_PhysicsProperties) {
      if (!(this_present_PhysicsProperties && that_present_PhysicsProperties))
        return false;
      if (!this.PhysicsProperties.equals(that.PhysicsProperties))
        return false;
    }

    boolean this_present_Properties = true && this.isSetProperties();
    boolean that_present_Properties = true && that.isSetProperties();
    if (this_present_Properties || that_present_Properties) {
      if (!(this_present_Properties && that_present_Properties))
        return false;
      if (!this.Properties.equals(that.Properties))
        return false;
    }

    boolean this_present_Attachments = true && this.isSetAttachments();
    boolean that_present_Attachments = true && that.isSetAttachments();
    if (this_present_Attachments || that_present_Attachments) {
      if (!(this_present_Attachments && that_present_Attachments))
        return false;
      if (!this.Attachments.equals(that.Attachments))
        return false;
    }

    boolean this_present_Constraints = true && this.isSetConstraints();
    boolean that_present_Constraints = true && that.isSetConstraints();
    if (this_present_Constraints || that_present_Constraints) {
      if (!(this_present_Constraints && that_present_Constraints))
        return false;
      if (!this.Constraints.equals(that.Constraints))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetID()) ? 131071 : 524287);
    if (isSetID())
      hashCode = hashCode * 8191 + ID.hashCode();

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + Name.hashCode();

    hashCode = hashCode * 8191 + ((isSetTransform()) ? 131071 : 524287);
    if (isSetTransform())
      hashCode = hashCode * 8191 + Transform.hashCode();

    hashCode = hashCode * 8191 + ((isSetCollider()) ? 131071 : 524287);
    if (isSetCollider())
      hashCode = hashCode * 8191 + Collider.hashCode();

    hashCode = hashCode * 8191 + ((isSetMesh()) ? 131071 : 524287);
    if (isSetMesh())
      hashCode = hashCode * 8191 + Mesh.hashCode();

    hashCode = hashCode * 8191 + ((isSetPhysicsProperties()) ? 131071 : 524287);
    if (isSetPhysicsProperties())
      hashCode = hashCode * 8191 + PhysicsProperties.hashCode();

    hashCode = hashCode * 8191 + ((isSetProperties()) ? 131071 : 524287);
    if (isSetProperties())
      hashCode = hashCode * 8191 + Properties.hashCode();

    hashCode = hashCode * 8191 + ((isSetAttachments()) ? 131071 : 524287);
    if (isSetAttachments())
      hashCode = hashCode * 8191 + Attachments.hashCode();

    hashCode = hashCode * 8191 + ((isSetConstraints()) ? 131071 : 524287);
    if (isSetConstraints())
      hashCode = hashCode * 8191 + Constraints.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MSceneObject other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetID()).compareTo(other.isSetID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ID, other.ID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Name, other.Name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTransform()).compareTo(other.isSetTransform());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransform()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Transform, other.Transform);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCollider()).compareTo(other.isSetCollider());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCollider()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Collider, other.Collider);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMesh()).compareTo(other.isSetMesh());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMesh()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Mesh, other.Mesh);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPhysicsProperties()).compareTo(other.isSetPhysicsProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPhysicsProperties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.PhysicsProperties, other.PhysicsProperties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProperties()).compareTo(other.isSetProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProperties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Properties, other.Properties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAttachments()).compareTo(other.isSetAttachments());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttachments()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Attachments, other.Attachments);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetConstraints()).compareTo(other.isSetConstraints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConstraints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Constraints, other.Constraints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MSceneObject(");
    boolean first = true;

    sb.append("ID:");
    if (this.ID == null) {
      sb.append("null");
    } else {
      sb.append(this.ID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Name:");
    if (this.Name == null) {
      sb.append("null");
    } else {
      sb.append(this.Name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Transform:");
    if (this.Transform == null) {
      sb.append("null");
    } else {
      sb.append(this.Transform);
    }
    first = false;
    if (isSetCollider()) {
      if (!first) sb.append(", ");
      sb.append("Collider:");
      if (this.Collider == null) {
        sb.append("null");
      } else {
        sb.append(this.Collider);
      }
      first = false;
    }
    if (isSetMesh()) {
      if (!first) sb.append(", ");
      sb.append("Mesh:");
      if (this.Mesh == null) {
        sb.append("null");
      } else {
        sb.append(this.Mesh);
      }
      first = false;
    }
    if (isSetPhysicsProperties()) {
      if (!first) sb.append(", ");
      sb.append("PhysicsProperties:");
      if (this.PhysicsProperties == null) {
        sb.append("null");
      } else {
        sb.append(this.PhysicsProperties);
      }
      first = false;
    }
    if (isSetProperties()) {
      if (!first) sb.append(", ");
      sb.append("Properties:");
      if (this.Properties == null) {
        sb.append("null");
      } else {
        sb.append(this.Properties);
      }
      first = false;
    }
    if (isSetAttachments()) {
      if (!first) sb.append(", ");
      sb.append("Attachments:");
      if (this.Attachments == null) {
        sb.append("null");
      } else {
        sb.append(this.Attachments);
      }
      first = false;
    }
    if (isSetConstraints()) {
      if (!first) sb.append(", ");
      sb.append("Constraints:");
      if (this.Constraints == null) {
        sb.append("null");
      } else {
        sb.append(this.Constraints);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (ID == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ID' was not present! Struct: " + toString());
    }
    if (Name == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'Name' was not present! Struct: " + toString());
    }
    if (Transform == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'Transform' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (Transform != null) {
      Transform.validate();
    }
    if (Collider != null) {
      Collider.validate();
    }
    if (Mesh != null) {
      Mesh.validate();
    }
    if (PhysicsProperties != null) {
      PhysicsProperties.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MSceneObjectStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MSceneObjectStandardScheme getScheme() {
      return new MSceneObjectStandardScheme();
    }
  }

  private static class MSceneObjectStandardScheme extends org.apache.thrift.scheme.StandardScheme<MSceneObject> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MSceneObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ID = iprot.readString();
              struct.setIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TRANSFORM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.Transform = new de.mosim.mmi.math.MTransform();
              struct.Transform.read(iprot);
              struct.setTransformIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // COLLIDER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.Collider = new MCollider();
              struct.Collider.read(iprot);
              struct.setColliderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // MESH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.Mesh = new MMesh();
              struct.Mesh.read(iprot);
              struct.setMeshIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PHYSICS_PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.PhysicsProperties = new MPhysicsProperties();
              struct.PhysicsProperties.read(iprot);
              struct.setPhysicsPropertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map226 = iprot.readMapBegin();
                struct.Properties = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map226.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key227;
                @org.apache.thrift.annotation.Nullable java.lang.String _val228;
                for (int _i229 = 0; _i229 < _map226.size; ++_i229)
                {
                  _key227 = iprot.readString();
                  _val228 = iprot.readString();
                  struct.Properties.put(_key227, _val228);
                }
                iprot.readMapEnd();
              }
              struct.setPropertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // ATTACHMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list230 = iprot.readListBegin();
                struct.Attachments = new java.util.ArrayList<MAttachment>(_list230.size);
                @org.apache.thrift.annotation.Nullable MAttachment _elem231;
                for (int _i232 = 0; _i232 < _list230.size; ++_i232)
                {
                  _elem231 = new MAttachment();
                  _elem231.read(iprot);
                  struct.Attachments.add(_elem231);
                }
                iprot.readListEnd();
              }
              struct.setAttachmentsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // CONSTRAINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list233 = iprot.readListBegin();
                struct.Constraints = new java.util.ArrayList<de.mosim.mmi.constraints.MConstraint>(_list233.size);
                @org.apache.thrift.annotation.Nullable de.mosim.mmi.constraints.MConstraint _elem234;
                for (int _i235 = 0; _i235 < _list233.size; ++_i235)
                {
                  _elem234 = new de.mosim.mmi.constraints.MConstraint();
                  _elem234.read(iprot);
                  struct.Constraints.add(_elem234);
                }
                iprot.readListEnd();
              }
              struct.setConstraintsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MSceneObject struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ID != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.ID);
        oprot.writeFieldEnd();
      }
      if (struct.Name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.Name);
        oprot.writeFieldEnd();
      }
      if (struct.Transform != null) {
        oprot.writeFieldBegin(TRANSFORM_FIELD_DESC);
        struct.Transform.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.Collider != null) {
        if (struct.isSetCollider()) {
          oprot.writeFieldBegin(COLLIDER_FIELD_DESC);
          struct.Collider.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.Mesh != null) {
        if (struct.isSetMesh()) {
          oprot.writeFieldBegin(MESH_FIELD_DESC);
          struct.Mesh.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.PhysicsProperties != null) {
        if (struct.isSetPhysicsProperties()) {
          oprot.writeFieldBegin(PHYSICS_PROPERTIES_FIELD_DESC);
          struct.PhysicsProperties.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.Properties != null) {
        if (struct.isSetProperties()) {
          oprot.writeFieldBegin(PROPERTIES_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.Properties.size()));
            for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter236 : struct.Properties.entrySet())
            {
              oprot.writeString(_iter236.getKey());
              oprot.writeString(_iter236.getValue());
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.Attachments != null) {
        if (struct.isSetAttachments()) {
          oprot.writeFieldBegin(ATTACHMENTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.Attachments.size()));
            for (MAttachment _iter237 : struct.Attachments)
            {
              _iter237.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.Constraints != null) {
        if (struct.isSetConstraints()) {
          oprot.writeFieldBegin(CONSTRAINTS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.Constraints.size()));
            for (de.mosim.mmi.constraints.MConstraint _iter238 : struct.Constraints)
            {
              _iter238.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MSceneObjectTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MSceneObjectTupleScheme getScheme() {
      return new MSceneObjectTupleScheme();
    }
  }

  private static class MSceneObjectTupleScheme extends org.apache.thrift.scheme.TupleScheme<MSceneObject> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MSceneObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.ID);
      oprot.writeString(struct.Name);
      struct.Transform.write(oprot);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCollider()) {
        optionals.set(0);
      }
      if (struct.isSetMesh()) {
        optionals.set(1);
      }
      if (struct.isSetPhysicsProperties()) {
        optionals.set(2);
      }
      if (struct.isSetProperties()) {
        optionals.set(3);
      }
      if (struct.isSetAttachments()) {
        optionals.set(4);
      }
      if (struct.isSetConstraints()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetCollider()) {
        struct.Collider.write(oprot);
      }
      if (struct.isSetMesh()) {
        struct.Mesh.write(oprot);
      }
      if (struct.isSetPhysicsProperties()) {
        struct.PhysicsProperties.write(oprot);
      }
      if (struct.isSetProperties()) {
        {
          oprot.writeI32(struct.Properties.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter239 : struct.Properties.entrySet())
          {
            oprot.writeString(_iter239.getKey());
            oprot.writeString(_iter239.getValue());
          }
        }
      }
      if (struct.isSetAttachments()) {
        {
          oprot.writeI32(struct.Attachments.size());
          for (MAttachment _iter240 : struct.Attachments)
          {
            _iter240.write(oprot);
          }
        }
      }
      if (struct.isSetConstraints()) {
        {
          oprot.writeI32(struct.Constraints.size());
          for (de.mosim.mmi.constraints.MConstraint _iter241 : struct.Constraints)
          {
            _iter241.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MSceneObject struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.ID = iprot.readString();
      struct.setIDIsSet(true);
      struct.Name = iprot.readString();
      struct.setNameIsSet(true);
      struct.Transform = new de.mosim.mmi.math.MTransform();
      struct.Transform.read(iprot);
      struct.setTransformIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.Collider = new MCollider();
        struct.Collider.read(iprot);
        struct.setColliderIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Mesh = new MMesh();
        struct.Mesh.read(iprot);
        struct.setMeshIsSet(true);
      }
      if (incoming.get(2)) {
        struct.PhysicsProperties = new MPhysicsProperties();
        struct.PhysicsProperties.read(iprot);
        struct.setPhysicsPropertiesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map242 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.Properties = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map242.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key243;
          @org.apache.thrift.annotation.Nullable java.lang.String _val244;
          for (int _i245 = 0; _i245 < _map242.size; ++_i245)
          {
            _key243 = iprot.readString();
            _val244 = iprot.readString();
            struct.Properties.put(_key243, _val244);
          }
        }
        struct.setPropertiesIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list246 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.Attachments = new java.util.ArrayList<MAttachment>(_list246.size);
          @org.apache.thrift.annotation.Nullable MAttachment _elem247;
          for (int _i248 = 0; _i248 < _list246.size; ++_i248)
          {
            _elem247 = new MAttachment();
            _elem247.read(iprot);
            struct.Attachments.add(_elem247);
          }
        }
        struct.setAttachmentsIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list249 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.Constraints = new java.util.ArrayList<de.mosim.mmi.constraints.MConstraint>(_list249.size);
          @org.apache.thrift.annotation.Nullable de.mosim.mmi.constraints.MConstraint _elem250;
          for (int _i251 = 0; _i251 < _list249.size; ++_i251)
          {
            _elem250 = new de.mosim.mmi.constraints.MConstraint();
            _elem250.read(iprot);
            struct.Constraints.add(_elem250);
          }
        }
        struct.setConstraintsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

