/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MMIStandard
{
  public enum MColliderType
  {
    Box = 0,
    Sphere = 1,
    Capsule = 2,
    Cone = 3,
    Cylinder = 4,
    Mesh = 5,
    Custom = 6,
  }
}
