/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace MMIStandard
{
  public static class mmiConstants
  {
    public const string MSimulationEvent_Start = "start";
    public const string MSimulationEvent_Ready = "ready";
    public const string MSimulationEvent_Stroke_Start = "stroke_start";
    public const string MSimulationEvent_Stroke = "stroke";
    public const string MSimulationEvent_Stroke_End = "stroke_end";
    public const string MSimulationEvent_End = "end";
    public const string MSimulationEvent_Abort = "abort";
    public const string MSimulationEvent_Warning = "warning";
    public const string MSimulationEvent_Exception = "exception";
    public const string MSimulationEvent_InitError = "initError";
    public const string MSimulationEvent_CycleEnd = "cycleEnd";
  }
}
