/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MMIStandard
{
  public enum MPhysicsInteractionType
  {
    AddForce = 0,
    AddTorque = 1,
    ChangeVelocity = 2,
    ChangeAngularVelocity = 3,
    ChangeMass = 4,
    ChangeCenterOfMass = 5,
    ChangeInertia = 6,
  }
}
