/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AJAN_constants.h"

namespace MMIStandard {

const AJANConstants g_AJAN_constants;

AJANConstants::AJANConstants() {
}

} // namespace

