<?php
/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MCoSimulationAccess_UnregisterAtEvent_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'clientAddress',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\MIPAddress',
        ),
        2 => array(
            'var' => 'eventType',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \MIPAddress
     */
    public $clientAddress = null;
    /**
     * @var string
     */
    public $eventType = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['clientAddress'])) {
                $this->clientAddress = $vals['clientAddress'];
            }
            if (isset($vals['eventType'])) {
                $this->eventType = $vals['eventType'];
            }
        }
    }

    public function getName()
    {
        return 'MCoSimulationAccess_UnregisterAtEvent_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->clientAddress = new \MIPAddress();
                        $xfer += $this->clientAddress->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->eventType);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MCoSimulationAccess_UnregisterAtEvent_args');
        if ($this->clientAddress !== null) {
            if (!is_object($this->clientAddress)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('clientAddress', TType::STRUCT, 1);
            $xfer += $this->clientAddress->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->eventType !== null) {
            $xfer += $output->writeFieldBegin('eventType', TType::STRING, 2);
            $xfer += $output->writeString($this->eventType);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
