<?php
/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MParameter
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'Name',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'Type',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'Description',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'Required',
            'isRequired' => true,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var string
     */
    public $Name = null;
    /**
     * @var string
     */
    public $Type = null;
    /**
     * @var string
     */
    public $Description = null;
    /**
     * @var bool
     */
    public $Required = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['Name'])) {
                $this->Name = $vals['Name'];
            }
            if (isset($vals['Type'])) {
                $this->Type = $vals['Type'];
            }
            if (isset($vals['Description'])) {
                $this->Description = $vals['Description'];
            }
            if (isset($vals['Required'])) {
                $this->Required = $vals['Required'];
            }
        }
    }

    public function getName()
    {
        return 'MParameter';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Type);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Description);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->Required);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MParameter');
        if ($this->Name !== null) {
            $xfer += $output->writeFieldBegin('Name', TType::STRING, 1);
            $xfer += $output->writeString($this->Name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Type !== null) {
            $xfer += $output->writeFieldBegin('Type', TType::STRING, 2);
            $xfer += $output->writeString($this->Type);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Description !== null) {
            $xfer += $output->writeFieldBegin('Description', TType::STRING, 3);
            $xfer += $output->writeString($this->Description);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Required !== null) {
            $xfer += $output->writeFieldBegin('Required', TType::BOOL, 4);
            $xfer += $output->writeBool($this->Required);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
