<?php
/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MSceneObjectUpdate
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'ID',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'Name',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'Transform',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\MTransformUpdate',
        ),
        4 => array(
            'var' => 'Collider',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\MCollider',
        ),
        5 => array(
            'var' => 'Mesh',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\MMesh',
        ),
        6 => array(
            'var' => 'PhysicsProperties',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\MPhysicsProperties',
        ),
        7 => array(
            'var' => 'HandPoses',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\MHandPose',
                ),
        ),
        8 => array(
            'var' => 'Properties',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\MPropertyUpdate',
                ),
        ),
        9 => array(
            'var' => 'Attachments',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\MAttachment',
                ),
        ),
        10 => array(
            'var' => 'Constraints',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\MConstraint',
                ),
        ),
    );

    /**
     * @var string
     */
    public $ID = null;
    /**
     * @var string
     */
    public $Name = null;
    /**
     * @var \MTransformUpdate
     */
    public $Transform = null;
    /**
     * @var \MCollider
     */
    public $Collider = null;
    /**
     * @var \MMesh
     */
    public $Mesh = null;
    /**
     * @var \MPhysicsProperties
     */
    public $PhysicsProperties = null;
    /**
     * @var \MHandPose[]
     */
    public $HandPoses = null;
    /**
     * @var \MPropertyUpdate[]
     */
    public $Properties = null;
    /**
     * @var \MAttachment[]
     */
    public $Attachments = null;
    /**
     * @var \MConstraint[]
     */
    public $Constraints = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ID'])) {
                $this->ID = $vals['ID'];
            }
            if (isset($vals['Name'])) {
                $this->Name = $vals['Name'];
            }
            if (isset($vals['Transform'])) {
                $this->Transform = $vals['Transform'];
            }
            if (isset($vals['Collider'])) {
                $this->Collider = $vals['Collider'];
            }
            if (isset($vals['Mesh'])) {
                $this->Mesh = $vals['Mesh'];
            }
            if (isset($vals['PhysicsProperties'])) {
                $this->PhysicsProperties = $vals['PhysicsProperties'];
            }
            if (isset($vals['HandPoses'])) {
                $this->HandPoses = $vals['HandPoses'];
            }
            if (isset($vals['Properties'])) {
                $this->Properties = $vals['Properties'];
            }
            if (isset($vals['Attachments'])) {
                $this->Attachments = $vals['Attachments'];
            }
            if (isset($vals['Constraints'])) {
                $this->Constraints = $vals['Constraints'];
            }
        }
    }

    public function getName()
    {
        return 'MSceneObjectUpdate';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Name);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->Transform = new \MTransformUpdate();
                        $xfer += $this->Transform->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRUCT) {
                        $this->Collider = new \MCollider();
                        $xfer += $this->Collider->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRUCT) {
                        $this->Mesh = new \MMesh();
                        $xfer += $this->Mesh->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRUCT) {
                        $this->PhysicsProperties = new \MPhysicsProperties();
                        $xfer += $this->PhysicsProperties->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::LST) {
                        $this->HandPoses = array();
                        $_size222 = 0;
                        $_etype225 = 0;
                        $xfer += $input->readListBegin($_etype225, $_size222);
                        for ($_i226 = 0; $_i226 < $_size222; ++$_i226) {
                            $elem227 = null;
                            $elem227 = new \MHandPose();
                            $xfer += $elem227->read($input);
                            $this->HandPoses []= $elem227;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::LST) {
                        $this->Properties = array();
                        $_size228 = 0;
                        $_etype231 = 0;
                        $xfer += $input->readListBegin($_etype231, $_size228);
                        for ($_i232 = 0; $_i232 < $_size228; ++$_i232) {
                            $elem233 = null;
                            $elem233 = new \MPropertyUpdate();
                            $xfer += $elem233->read($input);
                            $this->Properties []= $elem233;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::LST) {
                        $this->Attachments = array();
                        $_size234 = 0;
                        $_etype237 = 0;
                        $xfer += $input->readListBegin($_etype237, $_size234);
                        for ($_i238 = 0; $_i238 < $_size234; ++$_i238) {
                            $elem239 = null;
                            $elem239 = new \MAttachment();
                            $xfer += $elem239->read($input);
                            $this->Attachments []= $elem239;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::LST) {
                        $this->Constraints = array();
                        $_size240 = 0;
                        $_etype243 = 0;
                        $xfer += $input->readListBegin($_etype243, $_size240);
                        for ($_i244 = 0; $_i244 < $_size240; ++$_i244) {
                            $elem245 = null;
                            $elem245 = new \MConstraint();
                            $xfer += $elem245->read($input);
                            $this->Constraints []= $elem245;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MSceneObjectUpdate');
        if ($this->ID !== null) {
            $xfer += $output->writeFieldBegin('ID', TType::STRING, 1);
            $xfer += $output->writeString($this->ID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Name !== null) {
            $xfer += $output->writeFieldBegin('Name', TType::STRING, 2);
            $xfer += $output->writeString($this->Name);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Transform !== null) {
            if (!is_object($this->Transform)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Transform', TType::STRUCT, 3);
            $xfer += $this->Transform->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Collider !== null) {
            if (!is_object($this->Collider)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Collider', TType::STRUCT, 4);
            $xfer += $this->Collider->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Mesh !== null) {
            if (!is_object($this->Mesh)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Mesh', TType::STRUCT, 5);
            $xfer += $this->Mesh->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->PhysicsProperties !== null) {
            if (!is_object($this->PhysicsProperties)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('PhysicsProperties', TType::STRUCT, 6);
            $xfer += $this->PhysicsProperties->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->HandPoses !== null) {
            if (!is_array($this->HandPoses)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('HandPoses', TType::LST, 7);
            $output->writeListBegin(TType::STRUCT, count($this->HandPoses));
            foreach ($this->HandPoses as $iter246) {
                $xfer += $iter246->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Properties !== null) {
            if (!is_array($this->Properties)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Properties', TType::LST, 8);
            $output->writeListBegin(TType::STRUCT, count($this->Properties));
            foreach ($this->Properties as $iter247) {
                $xfer += $iter247->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Attachments !== null) {
            if (!is_array($this->Attachments)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Attachments', TType::LST, 9);
            $output->writeListBegin(TType::STRUCT, count($this->Attachments));
            foreach ($this->Attachments as $iter248) {
                $xfer += $iter248->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Constraints !== null) {
            if (!is_array($this->Constraints)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Constraints', TType::LST, 10);
            $output->writeListBegin(TType::STRUCT, count($this->Constraints));
            foreach ($this->Constraints as $iter249) {
                $xfer += $iter249->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
